spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://dpg-cu2h52rv2p9s738to0o0-a:5432/aiapplication_db
    username: ${DB_USERNAME:aiapplication_db_user}
    password: ${DB_PASSWORD:1a78iaMVaxHb5oN6bkp3nOEWGhMlXmrI}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  h2:
    console:
      enabled: false
  mvc:
    cors:
      allowed-origins: http://localhost:3000
      allowed-methods: GET,POST,PUT,DELETE
      allowed-headers: "*"

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

openai:
  api:
    key: ${OPENAI_SECRET}
